import {
  app,
  BrowserWindow,
  ipcMain,
  Menu,
  nativeImage,
  shell,
  Tray,
} from "electron";
import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { createServer } from "node:http";
import path from "node:path";
import type {
  AppConfig,
  AuthSessionStatus,
  ManagedChannel,
  SetupProgressEvent,
  UpdateStatusEvent,
  WorkspaceEditableFileName,
} from "../shared/types";
import { AutoUpdaterService } from "./services/auto-updater";
import { ConfigStore } from "./services/config-store";
import { EnvironmentService } from "./services/environment";
import { isGatewayRunningOutput } from "./services/parsers";
import { SetupOrchestrator } from "./services/setup-orchestrator";
import { SetupStore } from "./services/setup-store";
import { WorkspaceFilesService } from "./services/workspace-files";

const environmentService = new EnvironmentService();
const autoUpdaterService = new AutoUpdaterService();
let configStore: ConfigStore;
let setupOrchestrator: SetupOrchestrator;
const workspaceFilesService = new WorkspaceFilesService();
let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let isQuitting = false;
const pendingSetupEvents: SetupProgressEvent[] = [];
const pendingUpdateEvents: UpdateStatusEvent[] = [];
let trayGatewayRunning = false;
let activeAuthHandoff: Promise<AuthSessionStatus> | null = null;
const APP_PROTOCOL = "openclawdesktop";
let pendingProtocolUrl: string | null = null;

function extractProtocolUrl(argv: string[]): string | null {
  const match = argv.find((value) =>
    /^openclawdesktop:\/\//i.test(value.trim()),
  );
  return match ? match.trim() : null;
}

function handleProtocolOpen(url: string): void {
  pendingProtocolUrl = url;
  if (app.isReady()) {
    showMainWindow();
  }
}

function normalizeAuthBaseUrl(url: string): string {
  return url.replace(/\/+$/, "");
}

function resolveAuthBaseUrl(config: AppConfig): string {
  const envValue = process.env.OPENCLAW_AUTH_WEB_BASE_URL?.trim();
  if (envValue) {
    return normalizeAuthBaseUrl(envValue);
  }

  const configValue = config.authWebBaseUrl?.trim();
  if (configValue) {
    return normalizeAuthBaseUrl(configValue);
  }

  return "https://auth.openclawdesk.top";
}

async function getAuthSessionStatus(): Promise<AuthSessionStatus> {
  const config = await configStore.load();
  const baseUrl = resolveAuthBaseUrl(config);
  return {
    baseUrl,
    reachable: true,
    authenticated: Boolean(config.accountAuthorized),
    userId: config.accountUserId?.trim() ? config.accountUserId : null,
  };
}

function createDesktopCallbackCapture(
  expectedState: string,
  timeoutMs = 5 * 60 * 1000,
): Promise<{
  callbackUrl: string;
  tokenPromise: Promise<string>;
}> {
  return new Promise((resolve, reject) => {
    let settled = false;
    let resolved = false;
    let timeout: NodeJS.Timeout | null = null;
    let codeResolve: (value: string | PromiseLike<string>) => void = () => {};
    let codeReject: (reason?: unknown) => void = () => {};

    const server = createServer((request, response) => {
      const sendHtml = (statusCode: number, title: string, message: string) => {
        response.statusCode = statusCode;
        response.setHeader("content-type", "text/html; charset=utf-8");
        response.end(
          `<!doctype html><html><body style="font-family:Segoe UI,Arial,sans-serif;padding:24px"><h2>${title}</h2><p>${message}</p></body></html>`,
        );
      };

      if (!request.url) {
        sendHtml(400, "Invalid request", "Missing callback URL.");
        return;
      }

      const url = new URL(request.url, "http://127.0.0.1");
      if (url.pathname !== "/callback") {
        sendHtml(
          404,
          "Not found",
          "Use the desktop callback URL generated by OpenClaw Desktop.",
        );
        return;
      }

      const state = url.searchParams.get("state") ?? "";
      const token = url.searchParams.get("token") ?? "";
      const errorText = url.searchParams.get("error") ?? "";

      if (errorText) {
        sendHtml(
          400,
          "Sign-in failed",
          `Auth service returned an error: ${errorText}`,
        );
        return;
      }

      if (!state || state !== expectedState) {
        sendHtml(
          400,
          "Invalid callback",
          "State mismatch. Restart sign-in from the desktop app.",
        );
        return;
      }

      if (!token) {
        sendHtml(
          400,
          "Invalid callback",
          "Missing token. Restart sign-in from the desktop app.",
        );
        return;
      }

      sendHtml(
        200,
        "Connected",
        "OpenClaw Desktop is now linked. You can close this tab.",
      );
      settle(null, token);
    });

    const closeServer = () =>
      new Promise<void>((closeResolve) => {
        server.close(() => closeResolve());
      });

    const settle = (error: Error | null, code?: string) => {
      if (settled) {
        return;
      }
      settled = true;
      if (timeout) {
        clearTimeout(timeout);
      }
      void closeServer().finally(() => {
        if (error) {
          codeReject(error);
          return;
        }
        codeResolve(code ?? "");
      });
    };

    const codePromise = new Promise<string>((resolveCode, rejectCode) => {
      // Keep resolvers outside this scope for callback and timeout paths.
      codeResolve = resolveCode;
      codeReject = rejectCode;

      server.on("error", (error) => {
        const message = error instanceof Error ? error.message : String(error);
        const wrapped = new Error(`Auth callback server failed: ${message}`);
        if (!resolved) {
          reject(wrapped);
          resolved = true;
        }
        settle(wrapped);
      });

      timeout = setTimeout(() => {
        settle(new Error("Sign-in timed out. Please try again."));
      }, timeoutMs);

      server.listen(0, "127.0.0.1", () => {
        if (resolved) {
          return;
        }
        const address = server.address();
        if (!address || typeof address === "string") {
          const error = new Error("Could not bind local auth callback port.");
          resolved = true;
          reject(error);
          settle(error);
          return;
        }

        resolved = true;
        resolve({
          callbackUrl: `http://127.0.0.1:${address.port}/callback`,
          tokenPromise: codePromise,
        });
      });
    });
  });
}

async function runAuthHandoff(): Promise<AuthSessionStatus> {
  if (activeAuthHandoff) {
    return activeAuthHandoff;
  }

  activeAuthHandoff = (async () => {
    const config = await configStore.load();
    const baseUrl = resolveAuthBaseUrl(config);
    const state = randomBytes(24).toString("hex");

    try {
      const capture = await createDesktopCallbackCapture(state);
      const startUrl = new URL("/desktop/start", baseUrl);
      startUrl.searchParams.set("state", state);
      startUrl.searchParams.set("callback", capture.callbackUrl);

      await shell.openExternal(startUrl.toString());
      const token = await capture.tokenPromise;

      const exchangeUrl = new URL("/api/auth/desktop/exchange", baseUrl);
      const response = await fetch(exchangeUrl.toString(), {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json",
        },
        body: JSON.stringify({ token, state }),
      });

      const payload = (await response.json().catch(() => ({}))) as {
        authenticated?: unknown;
        userId?: unknown;
        error?: unknown;
      };

      if (!response.ok) {
        const detail =
          typeof payload.error === "string"
            ? payload.error
            : `Exchange failed (${response.status}).`;
        return {
          baseUrl,
          reachable: true,
          authenticated: false,
          userId: null,
          error: detail,
        };
      }

      const authenticated = payload.authenticated === true;
      const userId = typeof payload.userId === "string" ? payload.userId : null;

      await configStore.save({
        authWebBaseUrl: baseUrl,
        accountAuthorized: authenticated,
        accountUserId: authenticated ? (userId ?? "") : "",
      });

      return {
        baseUrl,
        reachable: true,
        authenticated,
        userId,
      };
    } catch (error) {
      return {
        baseUrl,
        reachable: false,
        authenticated: false,
        userId: null,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  })().finally(() => {
    activeAuthHandoff = null;
  });

  return activeAuthHandoff;
}

function resolvePreloadFile(): string {
  return path.join(__dirname, "..", "preload", "preload.js");
}

function resolveRendererFile(): string {
  const appPath = app.getAppPath();
  const reactRendererPath = path.join(
    appPath,
    "dist",
    "renderer-react",
    "index.html",
  );
  const legacyRendererPath = path.join(
    appPath,
    "dist",
    "renderer",
    "index.html",
  );
  const uiMode = (process.env.OPENCLAW_UI_EXPERIMENT || "react").toLowerCase();

  // React renderer is now the default. Set OPENCLAW_UI_EXPERIMENT=legacy to force the old UI.
  if (uiMode !== "legacy" && existsSync(reactRendererPath)) {
    return reactRendererPath;
  }

  return legacyRendererPath;
}

function resolveAppIconPath(): string {
  return path.join(
    app.getAppPath(),
    "assets",
    "branding",
    "openclaw_icon.icns",
  );
}

function applyMacDockIcon(): void {
  if (process.platform !== "darwin" || !app.dock) {
    return;
  }

  const iconPath = resolveAppIconPath();
  if (existsSync(iconPath)) {
    app.dock.setIcon(nativeImage.createFromPath(iconPath));
  }
}

function createWindow(): void {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 820,
    minWidth: 1024,
    minHeight: 700,
    show: false,
    title: "OpenClaw Desktop",
    backgroundColor: "#181818",
    icon: resolveAppIconPath(),
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: resolvePreloadFile(),
    },
  });

  let shown = false;
  const fallbackShowTimer = setTimeout(() => {
    if (!shown) {
      console.warn("[window] ready-to-show timed out; forcing window display.");
      showWindow("fallback-timeout");
    }
  }, 10_000);

  const clearFallbackTimer = () => {
    clearTimeout(fallbackShowTimer);
  };

  const showWindow = (reason: string) => {
    if (!mainWindow || mainWindow.isDestroyed() || shown) {
      return;
    }

    shown = true;
    clearFallbackTimer();
    console.info(`[window] showing main window (${reason}).`);

    flushPendingSetupEvents();
    flushPendingUpdateEvents();
    if (pendingProtocolUrl) {
      mainWindow.webContents.send("auth:protocol-open", pendingProtocolUrl);
      pendingProtocolUrl = null;
    }

    if (process.platform === "win32" && !mainWindow.isMaximized()) {
      mainWindow.maximize();
    }

    mainWindow.show();
  };

  void mainWindow.loadFile(resolveRendererFile());

  mainWindow.once("ready-to-show", () => {
    showWindow("ready-to-show");
  });

  mainWindow.webContents.once("did-finish-load", () => {
    if (!shown) {
      showWindow("did-finish-load");
    }
  });

  mainWindow.webContents.on(
    "did-fail-load",
    (_event, errorCode, errorDescription, validatedURL, isMainFrame) => {
      if (!isMainFrame) {
        return;
      }
      console.error(
        `[window] renderer failed to load (${errorCode}) ${errorDescription} at ${validatedURL}`,
      );
      showWindow("did-fail-load");
    },
  );

  mainWindow.webContents.on("render-process-gone", (_event, details) => {
    console.error(`[window] renderer process gone: ${details.reason}`);
  });

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url);
    return { action: "deny" };
  });

  mainWindow.webContents.on("will-navigate", (event, url) => {
    const currentUrl = mainWindow?.webContents.getURL() ?? "";
    if (url !== currentUrl) {
      event.preventDefault();
      void shell.openExternal(url);
    }
  });

  mainWindow.on("closed", () => {
    clearFallbackTimer();
    mainWindow = null;
  });

  mainWindow.on("close", (event) => {
    if (process.platform !== "win32" || isQuitting) {
      return;
    }

    event.preventDefault();
    mainWindow?.hide();
  });
}

function buildTrayIcon() {
  const image = nativeImage.createFromDataURL(
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAM1BMVEVHcEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAx8qYvAAAAEHRSTlMAECAwQFBgcICPn6+/z9/vH+xR+AAAAG9JREFUGNNjYIACRkYmZi5uHh4+AXY2bi4eHj4gHj4Bdg5uHm4efg5+QW4eQR4+QX4BQVFBYVFRSVlFXUNTTX1Dc0NTS1tbR1dPX4BLS0dXR09fQMjI20jIyNVQ2NjarA0NfVAADEQQYlF9MZqwAAAABJRU5ErkJggg==",
  );

  return process.platform === "win32"
    ? image.resize({ width: 16, height: 16 })
    : image;
}

function showMainWindow(): void {
  if (!mainWindow || mainWindow.isDestroyed()) {
    createWindow();
    return;
  }

  if (!mainWindow.isVisible()) {
    mainWindow.show();
  }

  if (mainWindow.isMinimized()) {
    mainWindow.restore();
  }

  mainWindow.focus();
}

function showTrayMessage(content: string, title = "OpenClaw Desktop"): void {
  if (!tray || process.platform !== "win32") {
    return;
  }

  tray.displayBalloon({
    title,
    content,
  });
}

async function refreshTrayGatewayStatus(showMessage = false): Promise<void> {
  try {
    const result = await environmentService.gatewayStatus();
    trayGatewayRunning =
      result.ok && isGatewayRunningOutput(`${result.stdout} ${result.stderr}`);
    tray?.setToolTip(
      `OpenClaw Desktop - Gateway ${trayGatewayRunning ? "Running" : "Stopped"}`,
    );
    if (tray) {
      tray.setContextMenu(buildTrayMenu());
    }

    if (showMessage) {
      const detail = result.ok
        ? trayGatewayRunning
          ? "Gateway is running."
          : "Gateway is stopped."
        : result.stderr || result.stdout || "Could not check gateway status.";
      showTrayMessage(detail, "Gateway Status");
    }
  } catch (error) {
    trayGatewayRunning = false;
    tray?.setToolTip("OpenClaw Desktop - Gateway Unknown");
    if (tray) {
      tray.setContextMenu(buildTrayMenu());
    }
    const detail = error instanceof Error ? error.message : String(error);
    if (showMessage) {
      showTrayMessage(detail, "Gateway Status");
    }
    console.warn(`[tray] gateway status refresh failed: ${detail}`);
  }
}

async function handleTrayGatewayStart(): Promise<void> {
  try {
    const result = await environmentService.gatewayStart();
    await refreshTrayGatewayStatus(false);
    const detail = result.ok
      ? "Gateway start requested."
      : result.stderr || result.stdout || "Gateway start failed.";
    showTrayMessage(detail, "Gateway Start");
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    showTrayMessage(detail, "Gateway Start");
    console.warn(`[tray] gateway start failed: ${detail}`);
  }
}

async function handleTrayGatewayStop(): Promise<void> {
  try {
    const result = await environmentService.gatewayStop();
    await refreshTrayGatewayStatus(false);
    const detail = result.ok
      ? "Gateway stop requested."
      : result.stderr || result.stdout || "Gateway stop failed.";
    showTrayMessage(detail, "Gateway Stop");
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    showTrayMessage(detail, "Gateway Stop");
    console.warn(`[tray] gateway stop failed: ${detail}`);
  }
}

function buildTrayMenu(): Menu {
  return Menu.buildFromTemplate([
    {
      label: `Gateway: ${trayGatewayRunning ? "Running" : "Stopped"}`,
      enabled: false,
    },
    {
      label: "Gateway Status",
      click: () => {
        void refreshTrayGatewayStatus(true).catch((error) => {
          const detail = error instanceof Error ? error.message : String(error);
          console.warn(`[tray] gateway status click failed: ${detail}`);
        });
      },
    },
    {
      label: "Start Gateway",
      click: () => {
        void handleTrayGatewayStart().catch((error) => {
          const detail = error instanceof Error ? error.message : String(error);
          console.warn(`[tray] gateway start click failed: ${detail}`);
        });
      },
    },
    {
      label: "Stop Gateway",
      click: () => {
        void handleTrayGatewayStop().catch((error) => {
          const detail = error instanceof Error ? error.message : String(error);
          console.warn(`[tray] gateway stop click failed: ${detail}`);
        });
      },
    },
    {
      type: "separator",
    },
    {
      label: "Open OpenClaw Desktop",
      click: () => {
        showMainWindow();
      },
    },
    {
      type: "separator",
    },
    {
      label: "Quit",
      click: () => {
        isQuitting = true;
        app.quit();
      },
    },
  ]);
}

function createTray(): void {
  if (tray) {
    return;
  }

  try {
    tray = new Tray(buildTrayIcon());
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    console.error(`[tray] failed to create system tray: ${detail}`);
    tray = null;
    return;
  }

  tray.setToolTip("OpenClaw Desktop - Gateway Unknown");
  tray.setContextMenu(buildTrayMenu());

  tray.on("click", () => {
    if (mainWindow && mainWindow.isVisible()) {
      mainWindow.hide();
      return;
    }

    showMainWindow();
  });

  void refreshTrayGatewayStatus(false).catch((error) => {
    const detail = error instanceof Error ? error.message : String(error);
    console.warn(`[tray] initial gateway refresh failed: ${detail}`);
  });
}

function broadcastSetupProgress(event: SetupProgressEvent): void {
  const setupLogLine = `[setup:${event.stage}:${event.source}] ${event.message}`;
  if (event.level === "error") {
    console.error(setupLogLine);
  } else if (event.level === "warning") {
    console.warn(setupLogLine);
  } else {
    console.info(setupLogLine);
  }

  if (!mainWindow || mainWindow.isDestroyed()) {
    pendingSetupEvents.push(event);
    if (pendingSetupEvents.length > 200) {
      pendingSetupEvents.shift();
    }
    return;
  }

  mainWindow.webContents.send("setup:progress", event);
}

function broadcastUpdateStatus(event: UpdateStatusEvent): void {
  if (!mainWindow || mainWindow.isDestroyed()) {
    pendingUpdateEvents.push(event);
    if (pendingUpdateEvents.length > 200) {
      pendingUpdateEvents.shift();
    }
    return;
  }

  mainWindow.webContents.send("update:status", event);
}

function flushPendingSetupEvents(): void {
  if (
    !mainWindow ||
    mainWindow.isDestroyed() ||
    pendingSetupEvents.length === 0
  ) {
    return;
  }

  for (const event of pendingSetupEvents) {
    mainWindow.webContents.send("setup:progress", event);
  }

  pendingSetupEvents.length = 0;
}

function flushPendingUpdateEvents(): void {
  if (
    !mainWindow ||
    mainWindow.isDestroyed() ||
    pendingUpdateEvents.length === 0
  ) {
    return;
  }

  for (const event of pendingUpdateEvents) {
    mainWindow.webContents.send("update:status", event);
  }

  pendingUpdateEvents.length = 0;
}

function resolveInstallNodeStage(message: string): SetupProgressEvent["stage"] {
  const normalized = message.toLowerCase();
  if (/username|password|account setup|default unix user/.test(normalized)) {
    return "awaiting_wsl_user_setup";
  }
  if (/homebrew|\bbrew\b/.test(normalized)) {
    return "installing_homebrew";
  }
  if (
    /node|npm|runtime|apt-get|dependency|dependencies|package/.test(normalized)
  ) {
    return "installing_runtime";
  }
  if (/wsl|ubuntu|distro/.test(normalized)) {
    return "installing_wsl";
  }
  return "installing_runtime";
}

function registerIpcHandlers(): void {
  ipcMain.handle("env:get-status", () =>
    environmentService.getEnvironmentStatus(),
  );
  ipcMain.handle("channels:get-status", () =>
    environmentService.getChannelStatuses(),
  );
  ipcMain.handle("channels:reconnect", (_event, channel: ManagedChannel) =>
    environmentService.reconnectChannel(channel),
  );
  ipcMain.handle("channels:disable", (_event, channel: ManagedChannel) =>
    environmentService.disableChannel(channel),
  );
  ipcMain.handle("telegram:configure", (_event, token: string) =>
    environmentService.configureTelegramBot(token),
  );
  ipcMain.handle("models:get-status", () =>
    environmentService.getModelStatus(),
  );
  ipcMain.handle("models:apply", (_event, provider: string, model: string) =>
    environmentService.applyModelSelection(provider, model),
  );
  ipcMain.handle(
    "models:save-api-key",
    (_event, provider: string, apiKey: string) =>
      environmentService.saveModelApiKey(provider, apiKey),
  );
  ipcMain.handle(
    "workspace-files:get",
    (_event, workspacePath: string, fileName: WorkspaceEditableFileName) =>
      workspaceFilesService.getFile(workspacePath, fileName),
  );
  ipcMain.handle(
    "workspace-files:save",
    (
      _event,
      workspacePath: string,
      fileName: WorkspaceEditableFileName,
      content: string,
    ) => workspaceFilesService.saveFile(workspacePath, fileName, content),
  );
  ipcMain.handle("always-on:get-status", () =>
    environmentService.getAlwaysOnGatewayStatus(),
  );
  ipcMain.handle("always-on:set-enabled", (_event, enabled: boolean) =>
    environmentService.setAlwaysOnGatewayEnabled(Boolean(enabled)),
  );
  ipcMain.handle("update:get-status", () => autoUpdaterService.getStatus());
  ipcMain.handle("update:check", () => autoUpdaterService.checkForUpdates());
  ipcMain.handle("update:install", () => {
    autoUpdaterService.installDownloadedUpdate();
  });
  ipcMain.handle("env:install-node", () =>
    environmentService.installNodeRuntime(),
  );
  ipcMain.handle("env:install-node-stream", () =>
    environmentService.installNodeRuntimeStreaming((line, stream) => {
      broadcastSetupProgress({
        timestamp: new Date().toISOString(),
        stage: resolveInstallNodeStage(line),
        level: stream === "stderr" ? "warning" : "info",
        source: stream,
        message: line,
      });
    }),
  );
  ipcMain.handle("env:open-wsl-user-setup", () =>
    environmentService.openWslUserSetup(),
  );
  ipcMain.handle("env:restart-computer", () =>
    environmentService.restartComputer(),
  );
  ipcMain.handle("env:install-openclaw", () =>
    environmentService.installOpenClaw(),
  );
  ipcMain.handle("env:install-openclaw-stream", () =>
    environmentService.installOpenClawStreaming((line, stream) => {
      broadcastSetupProgress({
        timestamp: new Date().toISOString(),
        stage: "installing_openclaw",
        level: stream === "stderr" ? "warning" : "info",
        source: stream,
        message: line,
      });
    }),
  );
  ipcMain.handle("env:run-onboarding", () =>
    environmentService.runOnboarding(),
  );

  ipcMain.handle("gateway:status", async () => {
    const result = await environmentService.gatewayStatus();
    await refreshTrayGatewayStatus(false);
    return result;
  });
  ipcMain.handle("gateway:start", async () => {
    const result = await environmentService.gatewayStart();
    await refreshTrayGatewayStatus(false);
    return result;
  });
  ipcMain.handle("gateway:start-stream", async () => {
    const result = await environmentService.gatewayStartStreaming(
      (line, stream) => {
        broadcastSetupProgress({
          timestamp: new Date().toISOString(),
          stage: "starting_gateway",
          level: stream === "stderr" ? "warning" : "info",
          source: stream,
          message: line,
        });
      },
    );
    await refreshTrayGatewayStatus(false);
    return result;
  });
  ipcMain.handle("gateway:stop", async () => {
    const result = await environmentService.gatewayStop();
    await refreshTrayGatewayStatus(false);
    return result;
  });
  ipcMain.handle(
    "gateway:call",
    async (_event, method: string, params: unknown, requestId?: string) => {
      const rid = requestId || `gw-main-${Date.now()}`;
      const startedAt = Date.now();
      console.info("[gateway:call]", {
        event: "start",
        requestId: rid,
        method,
      });
      try {
        const result = await environmentService.gatewayCall(method, params);
        const durationMs = Date.now() - startedAt;
        console.info("[gateway:call]", {
          event: "success",
          requestId: rid,
          method,
          durationMs,
        });
        // Debug: log response payload for chat methods so we can see the structure
        if (method === "chat.send" || method === "chat.history") {
          const snippet = JSON.stringify(result).slice(0, 1000);
          console.info(`[gateway:call] ${method} payload:`, snippet);
        }
        return result;
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.warn("[gateway:call]", {
          event: "error",
          requestId: rid,
          method,
          durationMs: Date.now() - startedAt,
          message,
        });
        throw new Error(message);
      }
    },
  );

  ipcMain.handle("auth:open-signin", async () => {
    const config = await configStore.load();
    const baseUrl = resolveAuthBaseUrl(config);
    await shell.openExternal(`${baseUrl}/sign-in`);
    return true;
  });
  ipcMain.handle("auth:handoff", () => runAuthHandoff());
  ipcMain.handle("auth:get-session", () => getAuthSessionStatus());

  ipcMain.handle("config:load", () => configStore.load());
  ipcMain.handle("config:save", (_event, config) => configStore.save(config));

  ipcMain.handle("setup:get-state", () => setupOrchestrator.getState());
  ipcMain.handle("setup:run-guided", () => setupOrchestrator.runGuidedSetup());
  ipcMain.handle("setup:complete-onboarding", () =>
    setupOrchestrator.completeOnboardingFromUi(),
  );

  ipcMain.handle("wizard:start", (_event, params) =>
    environmentService.wizardStart(params),
  );
  ipcMain.handle("wizard:next", (_event, sessionId, answer) =>
    environmentService.wizardNext(sessionId, answer),
  );
  ipcMain.handle("wizard:status", (_event, sessionId) =>
    environmentService.wizardStatus(sessionId),
  );
  ipcMain.handle("wizard:cancel", (_event, sessionId) =>
    environmentService.wizardCancel(sessionId),
  );
}

async function maybeAutoStartGateway(): Promise<void> {
  const config = await configStore.load();
  if (!config.autoStartGateway) {
    return;
  }

  const status = await environmentService.getEnvironmentStatus();
  if (!status.isWindows || !status.openClawInstalled) {
    return;
  }

  // Check if the gateway process is already running (even if the port isn't
  // ready yet). Starting a second instance while one is initializing causes
  // lock conflicts and SIGTERM restart loops.
  const gatewayStatus = await environmentService.gatewayStatus();
  const processRunning =
    gatewayStatus.ok &&
    /running|active|ok/i.test(
      `${gatewayStatus.stdout} ${gatewayStatus.stderr}`,
    );
  if (processRunning) {
    console.info(
      "[startup] gateway process already running; skipping auto-start.",
    );
    return;
  }

  console.info("[startup] gateway not running; auto-starting.");
  void environmentService.gatewayStart().catch((error) => {
    const detail = error instanceof Error ? error.message : String(error);
    console.warn(`[startup] auto-start gateway failed: ${detail}`);
  });
}

const gotSingleInstanceLock = app.requestSingleInstanceLock();
if (!gotSingleInstanceLock) {
  app.quit();
}

app.on("second-instance", (_event, argv) => {
  const url = extractProtocolUrl(argv);
  if (url) {
    handleProtocolOpen(url);
    return;
  }
  showMainWindow();
});

// open-url is macOS-only. On Windows, protocol URLs arrive via second-instance + process.argv.
if (process.platform === "darwin") {
  app.on("open-url", (event, url) => {
    event.preventDefault();
    if (/^openclawdesktop:\/\//i.test(url)) {
      handleProtocolOpen(url);
    }
  });
}

if (gotSingleInstanceLock) {
  app
    .whenReady()
    .then(async () => {
      if (process.defaultApp && process.argv.length >= 2) {
        app.setAsDefaultProtocolClient(APP_PROTOCOL, process.execPath, [
          path.resolve(process.argv[1] ?? ""),
        ]);
      } else {
        app.setAsDefaultProtocolClient(APP_PROTOCOL);
      }

      applyMacDockIcon();

      const launchUrl = extractProtocolUrl(process.argv);
      if (launchUrl) {
        pendingProtocolUrl = launchUrl;
      }

      configStore = new ConfigStore(app.getPath("userData"));
      setupOrchestrator = new SetupOrchestrator(
        environmentService,
        new SetupStore(app.getPath("userData")),
      );
      setupOrchestrator.onProgress((event) => {
        broadcastSetupProgress(event);
      });
      autoUpdaterService.onStatus((event) => {
        broadcastUpdateStatus(event);
      });
      registerIpcHandlers();
      createWindow();
      createTray();
      await maybeAutoStartGateway();
      autoUpdaterService.startBackgroundChecks();

      app.on("activate", () => {
        if (BrowserWindow.getAllWindows().length === 0 || !mainWindow) {
          createWindow();
          return;
        }

        showMainWindow();
      });
    })
    .catch((error) => {
      const detail = error instanceof Error ? error.message : String(error);
      console.error(`[app] startup failed: ${detail}`);
    });
}

app.on("before-quit", () => {
  isQuitting = true;
});

app.on("window-all-closed", () => {
  if (process.platform === "darwin") {
    return;
  }
  // Quit if the user requested it, or if the tray failed to create
  // (otherwise the app becomes impossible to exit).
  if (isQuitting || !tray || tray.isDestroyed()) {
    app.quit();
  }
});
